In [30]:
import pandas as pd
import pandas_datareader.data as pdr
import yfinance as yf
from datetime import datetime

In [44]:
def retrieve_stock_data(ticker_symbol):
    yf.pdr_override()
    start=datetime.strptime('2020-12-01',"%Y-%m-%d")
    end=datetime.strptime('2020-12-31',"%Y-%m-%d")
    df = pdr.get_data_yahoo(ticker_symbol, start,end)
    return df
df=retrieve_stock_data('TSLA')
df.head()

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2020-12-01,199.196671,199.283340,190.683334,194.919998,194.919998,120310500
2020-12-02,185.479996,190.513336,180.403336,189.606674,189.606674,143327100
2020-12-03,196.673340,199.656662,194.143326,197.793335,197.793335,127656000
2020-12-04,197.003326,199.679993,195.166672,199.679993,199.679993,88203900
2020-12-07,201.639999,216.263336,201.016663,213.919998,213.919998,168929100

In [45]:
mpg=pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/mpg.csv")
mpg.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [46]:
import xlwings as xw

In [47]:
mpg

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.0,2790,15.6,82,usa,ford mustang gl
394,44.0,4,97.0,52.0,2130,24.6,82,europe,vw pickup
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [48]:
xw.view(mpg)

XlwingsError: The interactive mode of xlwings is only supported on Windows and macOS. On Linux, you can use xlwings Server or xlwings Reader.